name: Lint MLflow Sample

on:
  push:
    paths:
      - 'mlflowsample.py'  # Solo dispara el workflow si este archivo cambia

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: Run flake8 on mlflowsample.py
      run: |
        flake8 mlflowsample.py

    - name: Run mlflowsample.py
      run: python mlflowsample.py
      